---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Download and upload installation files to nexus
  hosts: nexus 
  vars: 
    download_folder: /home/osaradmin/aidevops/nexus/downloads
    nexus_url: "http://{{ nexus }}:8081/repository/http-hosted/"
    user: "admin"
    password: "password123"
  roles: 
    - download-static

