# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: archive images
  hosts: localhost
  vars:
    archived_folder: "/tmp/archived"
    image_folder: "/tmp/images"    
  roles:    
    - docker-archive
    - docker-deploy