---
# tasks file for yum

- name: Template a file to yum repos
  copy:    
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
          {% for item in yum_kubernetes_repos %}
          [{{ item.name }}]
          name={{ item.name }}
          baseurl={{ nexus_url_base }}/repository/{{ item.name }}/
          enabled=1
          gpgcheck=0
          {% endfor %}
  become: yes 