---
# tasks file for yum
- name: Copy a new gpg files
  ansible.builtin.copy:
    src: "{{role_path}}/files/{{ item }}"
    dest: "/etc/pki/rpm-gpg/"
  with_items:
      - "7fa2af80.pub"
      - "gpg"
      - "gpgkey"
      - "RPM-GPG-KEY-CentOS-7"
  become: yes
  
- name: Template a file to yum repos
  ansible.builtin.template:
    src: deepops.repo.j2
    dest: /etc/yum.repos.d/deepops.repo
  become: yes