nexus: 192.168.56.109

kubernetes_packages:
  - name: kubelet-{{ kubernetes_version_rhel_package }}-0
    state: present
  - name: kubectl-{{ kubernetes_version_rhel_package }}-0
    state: present
  - name: kubeadm-{{ kubernetes_version_rhel_package }}-0
    state: present
  - name: kubernetes-cni
    state: present

binary_files: 
  - { file_name: "helm-v3.0.0-linux-amd64.tar.gz",  url: "https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz", directory: ""  }
  - { file_name: "nvidia-device-plugin.yml",        url: "https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta4/nvidia-device-plugin.yml", directory: "/NVIDIA/k8s-device-plugin/1.0.0-beta4" }
  - { file_name: "nvidia-docker",                   url: "https://raw.githubusercontent.com/NVIDIA/nvidia-docker/master/nvidia-docker", directory: "/NVIDIA/nvidia-docker/master" }
  - { file_name: "deploy.yaml",                     url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/baremetal/deploy.yaml", directory: "/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/baremetal" }
  - { file_name: "kube-flannel.yml",                url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml", directory: "/coreos/flannel/master/Documentation/" }

docker_images:
  - {tar_name: "dashboard", name: "kubernetesui/dashboard", version: "v2.2.0", repo: "docker.io"}
  - {tar_name: "metrics-scraper", name: "kubernetesui/metrics-scraper", version: "v1.0.6", repo: "docker.io"}
  - {tar_name: "flannel", name: "coreos/flannel", version: "v0.14.0", repo: "quay.io"}
  - {tar_name: "controller", name: "ingress-nginx/controller", version: "v0.46.0", repo: "k8s.gcr.io"}
  - {tar_name: "kube-webhook-certgen", name: "jettech/kube-webhook-certgen", version: "v1.5.1", repo: "docker.io"}
  - {tar_name: "kube-apiserver", name: "kube-apiserver", version: "v1.21.1", repo: "k8s.gcr.io"}
  - {tar_name: "kube-controller-manager", name: "kube-controller-manager", version: "v1.21.1", repo: "k8s.gcr.io"}
  - {tar_name: "kube-scheduler", name: "kube-scheduler", version: "v1.21.1", repo: "k8s.gcr.io"}
  - {tar_name: "kube-proxy", name: "kube-proxy", version: "v1.21.1", repo: "k8s.gcr.io"}
  - {tar_name: "pause", name: "pause", version: "3.4.1", repo: "k8s.gcr.io"}
  - {tar_name: "etcd", name: "etcd", version: "3.4.13-0", repo: "k8s.gcr.io"}
  - {tar_name: "coredns", name: "coredns/coredns", version: "v1.8.0", repo: "k8s.gcr.io"}

yum_RHEL7_os_repos:
  - {name: 'yum-centos', url: 'http://mirror.vtti.vt.edu/centos/7.9.2009/os/x86_64/', base: '/centos/7.9.2009/os/x86_64'}
  - {name: 'yum-centos-extras', url: 'http://mirror.es.its.nyu.edu/centos/7.9.2009/extras/x86_64/', base: '/centos/7.9.2009/extras/x86_64'}
  - {name: 'yum-centos-updates', url: 'http://mirror.vtti.vt.edu/centos/7.9.2009/updates/x86_64/', base: '/centos/7.9.2009/updates/x86_64'}
  - {name: 'yum-centosplus', url: 'http://mirror.cs.vt.edu/pub/CentOS/7.9.2009/centosplus/x86_64/', base: '/pub/CentOS/7.9.2009/centosplus/x86_64'}
  
yum_RHEL7_kubernetes_repos:
  - {name: 'yum-cuda', url: 'https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/', base: '/compute/cuda/repos/rhel7/x86_64'}
  - {name: 'yum-docker-ce-stable', url: 'https://download.docker.com/linux/centos/7/x86_64/stable', base: '/linux/centos/7/x86_64/stable'}
  - {name: 'yum-epel', url: 'https://dl.fedoraproject.org/pub/epel/7/x86_64/', base: '/pub/epel/7/x86_64'}
  - {name: 'yum-kubernetes', url: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64', base: '/yum/repos/kubernetes-el7-x86_64', gpg: ''}
  - {name: 'yum-libnvidia-container', url: 'https://nvidia.github.io/libnvidia-container/centos7/x86_64', base: '/libnvidia-container/centos7/x86_64', gpg: ''}
  - {name: 'yum-nvidia-container-runtime', url: 'https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64', base: '/nvidia-container-runtime/centos7/x86_64', gpg: ''}
  - {name: 'yum-nvidia-dgx-7', url: 'https://international.download.nvidia.com/dgx/repos/rhel7/', base: '/dgx/repos/rhel7/', gpg: ''}
  - {name: 'yum-nvidia-dgx-7-updates', url: 'https://international.download.nvidia.com/dgx/repos/rhel7-updates/', base: '/dgx/repos/rhel7-updates/',  gpg: ''}
  - {name: 'yum-nvidia-docker', url: 'https://nvidia.github.io/nvidia-docker/centos7/x86_64', base: '/centos7/x86_64',  gpg: ''}
  - {name: 'yum-nvidia-ml', url: 'https://developer.download.nvidia.com/compute/machine-learning/repos/rhel7/x86_64/', base: '/compute/machine-learning/repos/rhel7/x86_64/',  gpg: ''} 

yum_os_repos:
  - {name: 'yum-appstream', url: 'http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/', base: '/centos/8-stream/AppStream/x86_64/os'}
  - {name: 'yum-centos', url: 'http://mirror.vtti.vt.edu/centos/8/BaseOS/x86_64/os', base: '/centos/8/BaseOS/x86_64/os'}
  - {name: 'yum-centos-extras', url: 'http://mirror.vtti.vt.edu/centos/8/extras/x86_64/os', base: '/centos/8/extras/x86_64/os'}
  - {name: 'yum-centosplus', url: 'http://mirror.vtti.vt.edu/centos/8/centosplus/x86_64/os', base: '/centos/8/centosplus/x86_64/os'}
  
yum_kubernetes_repos:
  - {name: 'yum-docker-ce-stable', url: 'https://download.docker.com/linux/centos/8/x86_64/stable/', base: '/linux/centos/8/x86_64/stable'}
  - {name: 'yum-epel', url: 'https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/', base: '/pub/epel/8/Everything/x86_64'}
  - {name: 'yum-kubernetes', url: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64', base: '/yum/repos/kubernetes-el7-x86_64', gpg: ''}  
  - {name: 'yum-cuda', url: 'https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/', base: '/compute/cuda/repos/rhel8/x86_64'}
  - {name: 'yum-libnvidia-container', url: 'https://nvidia.github.io/libnvidia-container/centos8/x86_64', base: '/libnvidia-container/centos8/x86_64', gpg: ''}
  - {name: 'yum-nvidia-container-runtime', url: 'https://nvidia.github.io/nvidia-container-runtime/centos8/x86_64', base: '/nvidia-container-runtime/centos8/x86_64', gpg: ''}
  - {name: 'yum-nvidia-docker', url: 'https://nvidia.github.io/nvidia-docker/centos8/x86_64', base: '/centos8/x86_64',  gpg: ''}
  - {name: 'yum-nvidia-ml', url: 'https://developer.download.nvidia.com/compute/machine-learning/repos/rhel8/x86_64/', base: '/compute/machine-learning/repos/rhel8/x86_64/',  gpg: ''} 

  # - {tar_name: "registry", name: "registry", version: "2.7", repo: "docker.io"}
  # - {tar_name: "k8s-helm", name: "lachlanevenson/k8s-helm", version: "v3.4.1", repo: "docker.io"}
  # - {tar_name: "node", name: "calico/node", version: "v3.15.2", repo: "docker.io"}
  # - {tar_name: "cni", name: "calico/cni", version: "v3.15.2", repo: "docker.io"}
  # - {tar_name: "kube-controllers", name: "calico/kube-controllers", version: "v3.15.2", repo: "docker.io"}  
  # - {tar_name: "kube-apiserver", name: "kube-apiserver", version: "v1.21.1", repo: "k8s.gcr.io"}
  # - {tar_name: "kube-controller-manager", name: "kube-controller-manager", version: "v1.21.1", repo: "k8s.gcr.io"}
  # - {tar_name: "kube-scheduler", name: "kube-scheduler", version: "v1.21.1", repo: "k8s.gcr.io"}
  # - {tar_name: "kube-proxy", name: "kube-proxy", version: "v1.21.1", repo: "k8s.gcr.io"}
  # - {tar_name: "pause", name: "pause", version: "3.4.1", repo: "k8s.gcr.io"}
  # - {tar_name: "etcd", name: "etcd", version: "3.4.13-0", repo: "k8s.gcr.io"}
  # - {tar_name: "coredns", name: "coredns/coredns", version: "v1.8.0", repo: "k8s.gcr.io"}
  # - {tar_name: "cluster-proportional-autoscaler-amd64", name: "cluster-proportional-autoscaler-amd64", version: "1.8.1", repo: "k8s.gcr.io"}
  # - {tar_name: "k8s-dns-node-cache", name: "k8s-dns-node-cache", version: "1.15.13", repo: "k8s.gcr.io"}
  # - {tar_name: "node-feature-discovery", name: "kubernetes_incubator/node-feature-discovery", version: "v0.6.0", repo: "quay.io"}
  # - {tar_name: "nfs-client-provisioner", name: "external_storage/nfs-client-provisioner", version: "v3.1.0-k8s1.11", repo: "quay.io"}




#quay.io/coreos/flannel:v0.14.0
#k8s.gcr.io/kube-apiserver:v1.21.1
#k8s.gcr.io/kube-controller-manager:v1.21.1
#k8s.gcr.io/kube-scheduler:v1.21.1
#k8s.gcr.io/kube-proxy:v1.21.1
#k8s.gcr.io/pause:3.4.1
#k8s.gcr.io/etcd:3.4.13-0
#k8s.gcr.io/coredns/coredns:v1.8.0

