- name: images
  command : 
    cmd: "docker pull {{ item.name }}:{{ item.version }}"
  loop: "{{ docker-images }}"   

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ archived_folder }}"
    state: directory
    mode: '0755'

- name: archive images
  ansible.builtin.shell: "docker save -o {{ archived_folder }}/{{ item.tar_name }}.tar {{ item.name }}:{{ item.version }}"
  loop: "{{ docker-images }}"