- name: images
  command : 
    cmd: "sudo docker pull {{ item.repo }}/{{ item.name }}:{{ item.version }}"
  loop: "{{ docker_images }}"   

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ archived_folder }}"
    state: directory
    mode: '0755'

- name: archive images
  command : 
    cmd: "sudo docker save -o {{ archived_folder }}/{{ item.tar_name }}.tar {{ item.repo }}/{{ item.name }}:{{ item.version }}"
  loop: "{{ docker_images }}"

- file:
    path: "{{ archived_folder }}"
    state: directory
    mode: 0755
  become: yes

- file:
    path: "{{ archived_folder }}/{{ item.tar_name }}.tar"
    state: touch
    mode: 0755
  loop: "{{ docker_images }}"
  become: yes