---
# tasks file for download-static
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ download_folder }}/"
    state: directory
    mode: '0755'

- name: Download file
  get_url:  
    url:  "{{ item.url }}"
    dest: "{{ download_folder }}/"
  loop: "{{ binary_files }}"
- name: Push file to nexus
  uri:
    url: "{{ nexus_url }}{{ item.directory }}/{{ item.file_name }}"
    method: PUT
    src: "{{ download_folder }}/{{ item.file_name }}"
    user: "{{ user }}"
    password: "{{ password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/octet-stream  
    status_code:
      - 201
  loop: "{{ binary_files }}"